# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Closet

on:
  push:
    branches: [release, master, dev]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        node-version: [13.x, 15.x]
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm run-script install-dependencies

      - name: Install and Build 🔧
        run: |
          npm install
          npm run-script build
