name: Deploy to GitHub Pages

on:
  push:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Dependencies 🔧
        run: |
          npm run-script install-dependencies

      - name: Install and Build 🔧
        run: |
          npm install
          npm run-script build:docs

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
          enable_jekyll: true

          user_name: Henrik Giesel
          user_email: hengiesel@gmail.com
